#!/usr/bin/env python
import cgi
import cgitb
cgitb.enable()
import os
import datetime


default = "No Value Present"


print("Content-Type: text/html")
print("")

this_day = datetime.datetime.today()

body = """<html>
<head>
<title>Lab 1 - CGI experiments by Dennis Lee</title>
</head>
<body>
<p>Hey there, this page has been generated by <i>{software}</i>, running <i>{script}</i>.</p>
<p>Today is <i>{month} {date}, {year}</i>.</p>
<p>This page was requested by IP Address <i>{client_ip}</i>.</p>
</body>
</html>""".format(
    software=os.environ.get('SERVER_SOFTWARE', default),
    script=os.environ.get('SCRIPT_NAME', default),
    month=this_day.strftime("%B"),
    date=this_day.day,
    year=this_day.year,
    client_ip=os.environ.get('REMOTE_ADDR')
)
print(body)
